### ISSUE TITLE
How to add a new entity to an existed crf model ? Or merge new model with old one?

### ISSUE THREAD

**Issue by eromoe** [TeamHG-Memex/sklearn-crfsuite#12]
Hi, 

I think it is a very common requirement.
Assume I already have a crf model tag entity to `cat` and  `dog` . now I also need to tag `mouse` entity.
What I have to do is :

1. retrain the crf model with all dataset, and use the new crf model
2. train another crf model using dataset only `mouse` taged.  use old model and new model together.

Very inefficient.

**Comment by kmike** [comment]
Closed in favor of https://github.com/scrapinghub/python-crfsuite/issues/60.
