### ISSUE TITLE
Can i make text segmentation in sklearn-crfsuite ?

### ISSUE THREAD

**Issue by wannaphongcom** [TeamHG-Memex/sklearn-crfsuite#13]
Can i make text segmentation in sklearn-crfsuite ? If you have any advice, please let me know.

**Comment by kmike** [comment]
Are there specific struggle points? Tutotial shows how to do Named Entity Recognition, which is just a text segmentation task with several "segment" classes (entities of various type, non-entities).

**Comment by wannaphongcom** [comment]
@kmike  Thank you, I ask questions about segmenting words. Can you recommend a word segment in sklearn-crfsuite ?

**Comment by kmike** [comment]
If you want to create a CRF word segmenter using sklearn-crfsuite then you need to find training data in a right format, define features and train a model, like for any other task. Sorry, I don't know anything prebuilt.
