### ISSUE TITLE
Mini-batch training

### ISSUE THREAD

**Issue by oasis789** [TeamHG-Memex/sklearn-crfsuite#15]
Does the CRF implementation support mini-batch training. Some sklearn predictors have a `partial_fit` method which supports incremental training. Would there be scope to extend the current implementation to include this?

**Comment by kmike** [comment]
Hey @oasis789,

It may be hard to implement, as the underlying C++ library (crfsuite) doesn't expose these interfaces.

**Comment by kmike** [comment]
See also: https://github.com/TeamHG-Memex/sklearn-crfsuite/issues/4 - usually the most memory-intensive part is feature dicts, not crfsuite; by using generators you can minimize the mount of dictionaries present in RAM at the same time.

**Comment by acepor** [comment]
@kmike Thanks for pointing out using generator. Could you please specify where we should use generator to reduce memory if we follow the [tutorial](https://sklearn-crfsuite.readthedocs.io/en/latest/tutorial.html). Many thanks!

**Comment by kmike** [comment]
@acepor replace

```py
%%time
X_train = [sent2features(s) for s in train_sents]
y_train = [sent2labels(s) for s in train_sents]

X_test = [sent2features(s) for s in test_sents]
y_test = [sent2labels(s) for s in test_sents]
``` 

with

```py
%%time
X_train = (sent2features(s) for s in train_sents)
y_train = [sent2labels(s) for s in train_sents]

X_test = (sent2features(s) for s in test_sents)
y_test = [sent2labels(s) for s in test_sents]
```

(see "Extract features from the data").

On my machine peak memory usage reduces from 590MB to 305MB after this change, and memory usage after training becomes 260MB instead of 565MB.

**Comment by acepor** [comment]
@kmike Yes, I felt the same way. BTW, i think modifying the following part may also reduce memory use:

```
def sent2features(sent):
    return [word2features(sent, i) for i in range(len(sent))]

def sent2labels(sent):
    return [label for token, postag, label in sent]

def sent2tokens(sent):
    return [token for token, postag, label in sent]
```

to 

```
def sent2features(sent):
    return (word2features(sent, i) for i in range(len(sent)))

def sent2labels(sent):
    return (label for token, postag, label in sent)

def sent2tokens(sent):
    return (token for token, postag, label in sent)
```

It seems that the memory use didn't drop much, but the time consumption reduced.

> peak memory: 2018.58 MiB, increment: 356.90 MiB
> CPU times: user 7min 3s, sys: 296 ms, total: 7min 3s
> 
> peak memory: 2076.94 MiB, increment: 360.37 MiB
> CPU times: user 6min 5s, sys: 236 ms, total: 6min 5s

However, this solution seems difficult in cross-validation. Do you have any suggestion? Maybe using `itertools.tee`?
