### ISSUE TITLE
Effective Feature Induction to Increase F1

### ISSUE THREAD

**Issue by emirceyani** [TeamHG-Memex/sklearn-crfsuite#17]
Hello,

I want to use some conjunctions of features to increase my F1 score. Is there any functionality to induce feature effectively?

Or 

Does sklearn-crfsuite support the algorithm described in this paper?
https://people.cs.umass.edu/~mccallum/papers/ifcrf-uai2003.pdf

Thanks

**Comment by emirceyani** [comment]
Ok,

Then I must implement a shallow parser to select which features affect most and add them explicitly.

Thank you very much for the quick reply

**Comment by kmike** [comment]
I just wanted to point out that with L1 regularization you will have to generate these features, but they will likely only affect performance (CPU, RAM) only in first few iterations of training; L1 is also a form of feature selection. After a first few iterations coefficients for most of such features are likely to become zero, and in CRFSuite it means they no longer affect computation and no longer take memory. 

You can also use simple heuristics to remove unneeded features, like dropping all features which appear in less than N sequences (e.g. N could be 2 or 5).

So I'd try this first, unless you've already tried it and figured out that L1/ElasticNet is still not enough, or unless you're specifically interested in implementing algorithm from McCallum's paper.
