### ISSUE TITLE
UnicodeEncodeError:

### ISSUE THREAD

**Issue by Ulitochka** [TeamHG-Memex/sklearn-crfsuite#32]
Hello! 
Thank you for your work.

I experiments with rissian texts. But I have this problem: 
`UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-3: ordinal not in range(128)`
I think that in my data set I have some strange symbols, but how I can find it?

python == 3.6
last version of sklearn-crfsuite

**Comment by weizhenzhao** [comment]
dear @Ulitochka 
do you fix this issue?
because I met the same issue as you
can you teach me how to solve it?

Thank you very much
weizhen

**Comment by Ulitochka** [comment]
Hi \ . /
In my case the problem was: I used symbols to denote classes. I replaced the characters with numbers (int()) and everything was ok

**Comment by DecideToLeave** [comment]
@weizhenzhao have you figure out your problem?

**Comment by Weber12321** [comment]
> symbols to denote classes. I replaced the char

Thank you sir, your solution help me a lot. I was also facing the same 'ascii' problem with Chinese dataset, and changing the tag sequence without symbols solved the problem.
