### ISSUE TITLE
Generators

### ISSUE THREAD

**Issue by Ulitochka** [TeamHG-Memex/sklearn-crfsuite#4]
Hello, thanks for your work.

Can I pass generators for my training features instead of the list of training features, to keep the memory overhead low? I mean: generators are supported?

**Comment by kmike** [comment]
Yes, generators are supported. But it seems currently you have to use verbose=False for them to work.

Note that the data will still be loaded to memory; you won't need to have all these Python dicts in memory at the same time, but the dataset will be still in RAM in the internal format (which should be much more compact though).

**Comment by DmytroBabenko** [comment]
In case of verobe=False, how can we be sure that training was successfully finished? 
I mean how can I know whether training was terminated with error code ("L-BFGS terminated with error code (-998)") or it was terminated by acceptation criteria ?
