### ISSUE TITLE
Is there an easy way to obtain a confusion matrix?

### ISSUE THREAD

**Issue by goerch** [TeamHG-Memex/sklearn-crfsuite#49]
I'm trying 

```
    confusion_matrix(y_test, y_pred)
```

with sklearn's method, but am getting the error message

```
ValueError: You appear to be using a legacy multi-label data representation. Sequence of sequences are no longer supported; use a binary array or sparse matrix instead - the MultiLabelBinarizer transformer can convert to this format.
```

**Comment by soerenetler** [comment]
Hi @goerch, I assume your y_true and y_pred are nested lists, right? For the confusion matrix function you have to flatten them first. Does that help?
Have a great weekend,
Sören

**Comment by goerch** [comment]
Thanks @soerenetler, excellent advice. I didn't bother to read the source before, but now I have

```
from sklearn_crfsuite.utils import flatten

mcm = multilabel_confusion_matrix(flatten(y_test), flatten(y_pred))
```
which works as intended.
