### ISSUE TITLE
How to save the trained CRF model?

### ISSUE THREAD

**Issue by acepor** [TeamHG-Memex/sklearn-crfsuite#5]
Thank you so much for the work.

I'm wondering if the trained model can be saved? In the API, CRF has a parameter model_filename to import the trained model, and it stated:

> By default, model files are created automatically and saved in temporary locations; the preferred way to save/load CRF models is to use pickle (or its alternatives like joblib)

How can we export the model to an explicit location?

Many thanks!

**Comment by kmike** [comment]
Hey @acepor,

To save a model you can use joblib or pickle:

```py
import joblib

# save:
joblib.dump(crf, 'mycrf.joblib')  #, compress=4) 

# load:
crf = joblib.load('mycrf.joblib')
```

Here is how it looks like with pickle:

```py
import pickle

# save:
with open('mycrf.joblib', 'wb') as f:
    pickle.dump(crf, f)

# load:
with open('mycrf.joblib', 'rb') as f:
    crf = pickle.load(f)
```

**Comment by acepor** [comment]
@kmike Thank you so much for the help.
