### ISSUE TITLE
crfsuite is spamming /tmp

### ISSUE THREAD

**Issue by severinsimmler** [TeamHG-Memex/sklearn-crfsuite#50]
Where do the `.crfsuite` files in my `/tmp` folder come from? Can I delete those or prevent being created?

![image](https://user-images.githubusercontent.com/16133277/81909507-fe43a580-95ca-11ea-9fad-a0cd16fc53ae.png)

**Comment by ttresaui** [comment]
Do you have solved this？i have the same problem now.

**Comment by severinsimmler** [comment]
No, but I think every time a `sklearn_crfsuite.CRF` object is initialized, `sklearn-crfsuite` creates this file for `pycrfsuite`. If your program crashes, this method won't get called:

https://github.com/TeamHG-Memex/sklearn-crfsuite/blob/293a2d00f9c8f2031dc093cd549d734c3b72cf47/sklearn_crfsuite/_fileresource.py#L30-L41

**TL;DR** I'd say you can delete those files, because they are artifacts of unexpected terminations.
