### ISSUE TITLE
ValueError: The numbers of items and labels differ: |x| = 230, |y| = 4

### ISSUE THREAD

**Issue by Lavanaraj** [TeamHG-Memex/sklearn-crfsuite#53]
![image](https://user-images.githubusercontent.com/36253790/84748304-10ec3880-afd6-11ea-9fe2-c42310b18425.png)

**Comment by ra2751** [comment]
Lavana, are you able to solve the above problem. I am facing the same in my case

**Comment by Dopamine-TX** [comment]
check your data type

**Comment by Dopamine-TX** [comment]
check your data.

**Comment by remo-help** [comment]
@ra2751 
I'm commenting here for future people who run into this issue since it was not explained here.

This happens if you pass CRFsuite data in a 1-D array or a list of dics. 

It expects a list of lists both for your X input data and y labels. See the source code:

`    def fit(self, X, y, X_dev=None, y_dev=None):
        """
        Train a model.

        Parameters
        ----------
        X : list of lists of dicts
            Feature dicts for several documents (in a python-crfsuite format).

        y : list of lists of strings
            Labels for several documents.
`

**Comment by BibekKoirala** [comment]
> @ra2751 I'm commenting here for future people who run into this issue since it was not explained here.
> 
> This happens if you pass CRFsuite data in a 1-D array or a list of dics.
> 
> It expects a list of lists both for your X input data and y labels. See the source code:
> 
> ```
>         Parameters
>         ----------
>         X : list of lists of dicts
>             Feature dicts for several documents (in a python-crfsuite format).
> 
>         y : list of lists of strings
>             Labels for several documents.
> ```

@remo-help Thank you so much  🙇‍♂️ ❤️
