### ISSUE TITLE
TypeError: expected bytes, NoneType found

### ISSUE THREAD

**Issue by Lavanaraj** [TeamHG-Memex/sklearn-crfsuite#54]
![image](https://user-images.githubusercontent.com/36253790/85750904-bd8d8f00-b727-11ea-9a72-58d200c064e7.png)

**Comment by chintanckg** [comment]
You need to convert your input text via sent2features function, after that you can pass the output your model to predict.

**Comment by shihanmax** [comment]
I also encountered this problem, converting int type labels to string works for me.
