### ISSUE TITLE
sklearn-crfsuite does not work on Ubuntu 14.04.5

### ISSUE THREAD

**Issue by azinnai** [TeamHG-Memex/sklearn-crfsuite#8]
Hi, 
I used sklearn-crfsuite on Ubuntu 16.04 without any problem. I had to downgrade my Ubuntu to 14.04.5 and now, when I try to import it, I get this error:

`ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version "GLIBCXX_3.4.21" not found (required by /home/ale/.local/lib/python2.7/site-packages/pycrfsuite/_pycrfsuite.so)`

The only suggested workarounds was to use dist-upgrade and I can't.

**Comment by kmike** [comment]
Hi @azinnai,

Can you try clearnig pip cache and reinstalling python-crfsuite? 

sklearn-crfsuite and python-crfsuite should work in Ubuntu 14.04, but compiled binaries are not necessarily compatible.
